[project]
name = "hermes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rainzee wang", email = "rainzee.w@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "msgspec>=0.21.1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 128
target-version = "py313"
